import * as dotenv from 'dotenv';
dotenv.config();
import { DataSource } from 'typeorm';

const url = process.env.DATABASE_URL ?? 'postgres://postgres:1234@localhost:5432/lisansustu';

const ds = new DataSource({
  type: 'postgres',
  url,
  ssl: url.includes('sslmode=require') ? { rejectUnauthorized: false } : undefined,
  synchronize: false,
});

const UNIVERSITIES: { name: string; city: string; type: 'devlet' | 'vakıf'; shortName?: string }[] = [
  // ── Devlet Üniversiteleri ──────────────────────────────────────────────────
  { name: 'Abant İzzet Baysal Üniversitesi', city: 'Bolu', type: 'devlet', shortName: 'AİBÜ' },
  { name: 'Abdullah Gül Üniversitesi', city: 'Kayseri', type: 'devlet', shortName: 'AGÜ' },
  { name: 'Adıyaman Üniversitesi', city: 'Adıyaman', type: 'devlet', shortName: 'ADYÜ' },
  { name: 'Adnan Menderes Üniversitesi', city: 'Aydın', type: 'devlet', shortName: 'ADÜ' },
  { name: 'Afyon Kocatepe Üniversitesi', city: 'Afyonkarahisar', type: 'devlet', shortName: 'AKÜ' },
  { name: 'Ağrı İbrahim Çeçen Üniversitesi', city: 'Ağrı', type: 'devlet', shortName: 'AİÇÜ' },
  { name: 'Akdeniz Üniversitesi', city: 'Antalya', type: 'devlet', shortName: 'AÜ' },
  { name: 'Aksaray Üniversitesi', city: 'Aksaray', type: 'devlet', shortName: 'ASÜ' },
  { name: 'Amasya Üniversitesi', city: 'Amasya', type: 'devlet', shortName: 'AMASYAÜ' },
  { name: 'Ankara Üniversitesi', city: 'Ankara', type: 'devlet', shortName: 'AÜ' },
  { name: 'Ankara Hacı Bayram Veli Üniversitesi', city: 'Ankara', type: 'devlet', shortName: 'AHBVÜ' },
  { name: 'Ankara Yıldırım Beyazıt Üniversitesi', city: 'Ankara', type: 'devlet', shortName: 'AYBÜ' },
  { name: 'Ankara Müzik ve Güzel Sanatlar Üniversitesi', city: 'Ankara', type: 'devlet', shortName: 'AMGÜ' },
  { name: 'Ardahan Üniversitesi', city: 'Ardahan', type: 'devlet', shortName: 'ARDÜ' },
  { name: 'Artvin Çoruh Üniversitesi', city: 'Artvin', type: 'devlet', shortName: 'AÇÜ' },
  { name: 'Atatürk Üniversitesi', city: 'Erzurum', type: 'devlet', shortName: 'ATAAÜ' },
  { name: 'Balıkesir Üniversitesi', city: 'Balıkesir', type: 'devlet', shortName: 'BAÜ' },
  { name: 'Bandırma Onyedi Eylül Üniversitesi', city: 'Balıkesir', type: 'devlet', shortName: 'BANDÜ' },
  { name: 'Bartın Üniversitesi', city: 'Bartın', type: 'devlet', shortName: 'BARÜ' },
  { name: 'Batman Üniversitesi', city: 'Batman', type: 'devlet', shortName: 'BATÜ' },
  { name: 'Bayburt Üniversitesi', city: 'Bayburt', type: 'devlet', shortName: 'BAYÜ' },
  { name: 'Bilecik Şeyh Edebali Üniversitesi', city: 'Bilecik', type: 'devlet', shortName: 'BŞEÜ' },
  { name: 'Bingöl Üniversitesi', city: 'Bingöl', type: 'devlet', shortName: 'BÜ' },
  { name: 'Bitlis Eren Üniversitesi', city: 'Bitlis', type: 'devlet', shortName: 'BEÜ' },
  { name: 'Boğaziçi Üniversitesi', city: 'İstanbul', type: 'devlet', shortName: 'BÜ' },
  { name: 'Burdur Mehmet Akif Ersoy Üniversitesi', city: 'Burdur', type: 'devlet', shortName: 'MAKÜ' },
  { name: 'Bursa Teknik Üniversitesi', city: 'Bursa', type: 'devlet', shortName: 'BTÜ' },
  { name: 'Bursa Uludağ Üniversitesi', city: 'Bursa', type: 'devlet', shortName: 'BUÜ' },
  { name: 'Çanakkale Onsekiz Mart Üniversitesi', city: 'Çanakkale', type: 'devlet', shortName: 'ÇOMÜ' },
  { name: 'Çankırı Karatekin Üniversitesi', city: 'Çankırı', type: 'devlet', shortName: 'ÇAKÜ' },
  { name: 'Çukurova Üniversitesi', city: 'Adana', type: 'devlet', shortName: 'ÇÜ' },
  { name: 'Cumhuriyet Üniversitesi', city: 'Sivas', type: 'devlet', shortName: 'CÜ' },
  { name: 'Dicle Üniversitesi', city: 'Diyarbakır', type: 'devlet', shortName: 'DÜ' },
  { name: 'Dokuz Eylül Üniversitesi', city: 'İzmir', type: 'devlet', shortName: 'DEÜ' },
  { name: 'Düzce Üniversitesi', city: 'Düzce', type: 'devlet', shortName: 'DÜ' },
  { name: 'Ege Üniversitesi', city: 'İzmir', type: 'devlet', shortName: 'EÜ' },
  { name: 'Erciyes Üniversitesi', city: 'Kayseri', type: 'devlet', shortName: 'ERÜ' },
  { name: 'Erzincan Binali Yıldırım Üniversitesi', city: 'Erzincan', type: 'devlet', shortName: 'EBY' },
  { name: 'Eskişehir Osmangazi Üniversitesi', city: 'Eskişehir', type: 'devlet', shortName: 'ESOGÜ' },
  { name: 'Eskişehir Teknik Üniversitesi', city: 'Eskişehir', type: 'devlet', shortName: 'ESTÜ' },
  { name: 'Fırat Üniversitesi', city: 'Elazığ', type: 'devlet', shortName: 'FÜ' },
  { name: 'Galatasaray Üniversitesi', city: 'İstanbul', type: 'devlet', shortName: 'GSÜ' },
  { name: 'Gazi Üniversitesi', city: 'Ankara', type: 'devlet', shortName: 'GÜ' },
  { name: 'Gaziantep Üniversitesi', city: 'Gaziantep', type: 'devlet', shortName: 'GAÜN' },
  { name: 'Gaziantep İslam Bilim ve Teknoloji Üniversitesi', city: 'Gaziantep', type: 'devlet', shortName: 'GİBTÜ' },
  { name: 'Gebze Teknik Üniversitesi', city: 'Kocaeli', type: 'devlet', shortName: 'GTÜ' },
  { name: 'Giresun Üniversitesi', city: 'Giresun', type: 'devlet', shortName: 'GRÜ' },
  { name: 'Gümüşhane Üniversitesi', city: 'Gümüşhane', type: 'devlet', shortName: 'GÜ' },
  { name: 'Hacettepe Üniversitesi', city: 'Ankara', type: 'devlet', shortName: 'HÜ' },
  { name: 'Hakkari Üniversitesi', city: 'Hakkari', type: 'devlet', shortName: 'HKÜ' },
  { name: 'Harran Üniversitesi', city: 'Şanlıurfa', type: 'devlet', shortName: 'HRÜ' },
  { name: 'Hitit Üniversitesi', city: 'Çorum', type: 'devlet', shortName: 'HİTÜ' },
  { name: 'Iğdır Üniversitesi', city: 'Iğdır', type: 'devlet', shortName: 'IGÜ' },
  { name: 'İnönü Üniversitesi', city: 'Malatya', type: 'devlet', shortName: 'İÜ' },
  { name: 'İskenderun Teknik Üniversitesi', city: 'Hatay', type: 'devlet', shortName: 'İSTE' },
  { name: 'İstanbul Teknik Üniversitesi', city: 'İstanbul', type: 'devlet', shortName: 'İTÜ' },
  { name: 'İstanbul Üniversitesi', city: 'İstanbul', type: 'devlet', shortName: 'İÜ' },
  { name: 'İstanbul Üniversitesi-Cerrahpaşa', city: 'İstanbul', type: 'devlet', shortName: 'İÜC' },
  { name: 'İstanbul Medeniyet Üniversitesi', city: 'İstanbul', type: 'devlet', shortName: 'İMÜ' },
  { name: 'İzmir Katip Çelebi Üniversitesi', city: 'İzmir', type: 'devlet', shortName: 'İKÇÜ' },
  { name: 'İzmir Demokrasi Üniversitesi', city: 'İzmir', type: 'devlet', shortName: 'İDÜ' },
  { name: 'İzmir Yüksek Teknoloji Enstitüsü', city: 'İzmir', type: 'devlet', shortName: 'İYTE' },
  { name: 'Kafkas Üniversitesi', city: 'Kars', type: 'devlet', shortName: 'KAÜ' },
  { name: 'Kahramanmaraş Sütçü İmam Üniversitesi', city: 'Kahramanmaraş', type: 'devlet', shortName: 'KSÜ' },
  { name: 'Kahramanmaraş İstiklal Üniversitesi', city: 'Kahramanmaraş', type: 'devlet', shortName: 'Kİ' },
  { name: 'Karabük Üniversitesi', city: 'Karabük', type: 'devlet', shortName: 'KBÜ' },
  { name: 'Karadeniz Teknik Üniversitesi', city: 'Trabzon', type: 'devlet', shortName: 'KTÜ' },
  { name: 'Kastamonu Üniversitesi', city: 'Kastamonu', type: 'devlet', shortName: 'KÜ' },
  { name: 'Kilis 7 Aralık Üniversitesi', city: 'Kilis', type: 'devlet', shortName: 'KİLİS7' },
  { name: 'Kırıkkale Üniversitesi', city: 'Kırıkkale', type: 'devlet', shortName: 'KKÜ' },
  { name: 'Kırklareli Üniversitesi', city: 'Kırklareli', type: 'devlet', shortName: 'KLÜ' },
  { name: 'Kırşehir Ahi Evran Üniversitesi', city: 'Kırşehir', type: 'devlet', shortName: 'AEÜ' },
  { name: 'Kocaeli Üniversitesi', city: 'Kocaeli', type: 'devlet', shortName: 'KOÜ' },
  { name: 'Konya Teknik Üniversitesi', city: 'Konya', type: 'devlet', shortName: 'KTÜN' },
  { name: 'Kütahya Dumlupınar Üniversitesi', city: 'Kütahya', type: 'devlet', shortName: 'DPÜ' },
  { name: 'Kütahya Sağlık Bilimleri Üniversitesi', city: 'Kütahya', type: 'devlet', shortName: 'KSBÜ' },
  { name: 'Malatya Turgut Özal Üniversitesi', city: 'Malatya', type: 'devlet', shortName: 'MTÖ' },
  { name: 'Manisa Celal Bayar Üniversitesi', city: 'Manisa', type: 'devlet', shortName: 'CBÜ' },
  { name: 'Mardin Artuklu Üniversitesi', city: 'Mardin', type: 'devlet', shortName: 'MAÜ' },
  { name: 'Mersin Üniversitesi', city: 'Mersin', type: 'devlet', shortName: 'MEÜ' },
  { name: 'Mimar Sinan Güzel Sanatlar Üniversitesi', city: 'İstanbul', type: 'devlet', shortName: 'MSGSÜ' },
  { name: 'Muğla Sıtkı Koçman Üniversitesi', city: 'Muğla', type: 'devlet', shortName: 'MSKÜ' },
  { name: 'Munzur Üniversitesi', city: 'Tunceli', type: 'devlet', shortName: 'MÜ' },
  { name: 'Muş Alparslan Üniversitesi', city: 'Muş', type: 'devlet', shortName: 'MAÜ' },
  { name: 'Necmettin Erbakan Üniversitesi', city: 'Konya', type: 'devlet', shortName: 'NEÜ' },
  { name: 'Nevşehir Hacı Bektaş Veli Üniversitesi', city: 'Nevşehir', type: 'devlet', shortName: 'NEVÜ' },
  { name: 'Niğde Ömer Halisdemir Üniversitesi', city: 'Niğde', type: 'devlet', shortName: 'NİĞDE' },
  { name: 'Ondokuz Mayıs Üniversitesi', city: 'Samsun', type: 'devlet', shortName: 'OMÜ' },
  { name: 'Orta Doğu Teknik Üniversitesi', city: 'Ankara', type: 'devlet', shortName: 'ODTÜ' },
  { name: 'Ordu Üniversitesi', city: 'Ordu', type: 'devlet', shortName: 'ODÜ' },
  { name: 'Osmaniye Korkut Ata Üniversitesi', city: 'Osmaniye', type: 'devlet', shortName: 'OKÜ' },
  { name: 'Pamukkale Üniversitesi', city: 'Denizli', type: 'devlet', shortName: 'PAÜ' },
  { name: 'Recep Tayyip Erdoğan Üniversitesi', city: 'Rize', type: 'devlet', shortName: 'RTEÜ' },
  { name: 'Sakarya Üniversitesi', city: 'Sakarya', type: 'devlet', shortName: 'SAÜ' },
  { name: 'Sakarya Uygulamalı Bilimler Üniversitesi', city: 'Sakarya', type: 'devlet', shortName: 'SUBÜ' },
  { name: 'Selçuk Üniversitesi', city: 'Konya', type: 'devlet', shortName: 'SÜ' },
  { name: 'Siirt Üniversitesi', city: 'Siirt', type: 'devlet', shortName: 'SİÜ' },
  { name: 'Sinop Üniversitesi', city: 'Sinop', type: 'devlet', shortName: 'SİNOP' },
  { name: 'Sivas Cumhuriyet Üniversitesi', city: 'Sivas', type: 'devlet', shortName: 'SCÜ' },
  { name: 'Süleyman Demirel Üniversitesi', city: 'Isparta', type: 'devlet', shortName: 'SDÜ' },
  { name: 'Isparta Uygulamalı Bilimler Üniversitesi', city: 'Isparta', type: 'devlet', shortName: 'ISUBÜ' },
  { name: 'Şırnak Üniversitesi', city: 'Şırnak', type: 'devlet', shortName: 'ŞÜ' },
  { name: 'Tekirdağ Namık Kemal Üniversitesi', city: 'Tekirdağ', type: 'devlet', shortName: 'NKÜ' },
  { name: 'Tokat Gaziosmanpaşa Üniversitesi', city: 'Tokat', type: 'devlet', shortName: 'GOP' },
  { name: 'Trabzon Üniversitesi', city: 'Trabzon', type: 'devlet', shortName: 'TRABZON' },
  { name: 'Trakya Üniversitesi', city: 'Edirne', type: 'devlet', shortName: 'TÜ' },
  { name: 'Türk-Alman Üniversitesi', city: 'İstanbul', type: 'devlet', shortName: 'TAÜ' },
  { name: 'Uşak Üniversitesi', city: 'Uşak', type: 'devlet', shortName: 'UŞAK' },
  { name: 'Van Yüzüncü Yıl Üniversitesi', city: 'Van', type: 'devlet', shortName: 'YYÜ' },
  { name: 'Yalova Üniversitesi', city: 'Yalova', type: 'devlet', shortName: 'YALOVAü' },
  { name: 'Yıldız Teknik Üniversitesi', city: 'İstanbul', type: 'devlet', shortName: 'YTÜ' },
  { name: 'Yozgat Bozok Üniversitesi', city: 'Yozgat', type: 'devlet', shortName: 'YOBU' },
  { name: 'Zonguldak Bülent Ecevit Üniversitesi', city: 'Zonguldak', type: 'devlet', shortName: 'BEÜ' },
  // ── Vakıf Üniversiteleri ──────────────────────────────────────────────────
  { name: 'Acıbadem Mehmet Ali Aydınlar Üniversitesi', city: 'İstanbul', type: 'vakıf', shortName: 'ACİBADEM' },
  { name: 'Altınbaş Üniversitesi', city: 'İstanbul', type: 'vakıf', shortName: 'ALTINBAŞ' },
  { name: 'Atılım Üniversitesi', city: 'Ankara', type: 'vakıf', shortName: 'ATILIM' },
  { name: 'Bahçeşehir Üniversitesi', city: 'İstanbul', type: 'vakıf', shortName: 'BAHÇEŞEHİR' },
  { name: 'Başkent Üniversitesi', city: 'Ankara', type: 'vakıf', shortName: 'BAŞKENT' },
  { name: 'Beykent Üniversitesi', city: 'İstanbul', type: 'vakıf', shortName: 'BEYKENT' },
  { name: 'Bezmiâlem Vakıf Üniversitesi', city: 'İstanbul', type: 'vakıf', shortName: 'BVÜ' },
  { name: 'Biruni Üniversitesi', city: 'İstanbul', type: 'vakıf', shortName: 'BİRUNİ' },
  { name: 'Çağ Üniversitesi', city: 'Mersin', type: 'vakıf', shortName: 'ÇAĞ' },
  { name: 'Çankaya Üniversitesi', city: 'Ankara', type: 'vakıf', shortName: 'ÇANKAYA' },
  { name: 'Doğuş Üniversitesi', city: 'İstanbul', type: 'vakıf', shortName: 'DOĞUŞ' },
  { name: 'Fatih Sultan Mehmet Vakıf Üniversitesi', city: 'İstanbul', type: 'vakıf', shortName: 'FSMVÜ' },
  { name: 'Fenerbahçe Üniversitesi', city: 'İstanbul', type: 'vakıf', shortName: 'FB' },
  { name: 'Hasan Kalyoncu Üniversitesi', city: 'Gaziantep', type: 'vakıf', shortName: 'HKÜ' },
  { name: 'İbn Haldun Üniversitesi', city: 'İstanbul', type: 'vakıf', shortName: 'İHÜ' },
  { name: 'İhsan Doğramacı Bilkent Üniversitesi', city: 'Ankara', type: 'vakıf', shortName: 'BİLKENT' },
  { name: 'İstanbul 29 Mayıs Üniversitesi', city: 'İstanbul', type: 'vakıf', shortName: '29MAYIS' },
  { name: 'İstanbul Aydın Üniversitesi', city: 'İstanbul', type: 'vakıf', shortName: 'İAÜ' },
  { name: 'İstanbul Bilgi Üniversitesi', city: 'İstanbul', type: 'vakıf', shortName: 'BİLGİ' },
  { name: 'İstanbul Esenyurt Üniversitesi', city: 'İstanbul', type: 'vakıf', shortName: 'ESENYURTü' },
  { name: 'İstanbul Gedik Üniversitesi', city: 'İstanbul', type: 'vakıf', shortName: 'GEDİK' },
  { name: 'İstanbul Gelişim Üniversitesi', city: 'İstanbul', type: 'vakıf', shortName: 'GELİŞİM' },
  { name: 'İstanbul Kent Üniversitesi', city: 'İstanbul', type: 'vakıf', shortName: 'KENT' },
  { name: 'İstanbul Kültür Üniversitesi', city: 'İstanbul', type: 'vakıf', shortName: 'İKÜ' },
  { name: 'İstanbul Medipol Üniversitesi', city: 'İstanbul', type: 'vakıf', shortName: 'MEDİPOL' },
  { name: 'İstanbul Nişantaşı Üniversitesi', city: 'İstanbul', type: 'vakıf', shortName: 'NİŞANTAŞI' },
  { name: 'İstanbul Okan Üniversitesi', city: 'İstanbul', type: 'vakıf', shortName: 'OKAN' },
  { name: 'İstanbul Rumeli Üniversitesi', city: 'İstanbul', type: 'vakıf', shortName: 'RUMELİ' },
  { name: 'İstanbul Sabahattin Zaim Üniversitesi', city: 'İstanbul', type: 'vakıf', shortName: 'İZÜ' },
  { name: 'İstanbul Ticaret Üniversitesi', city: 'İstanbul', type: 'vakıf', shortName: 'TİCARET' },
  { name: 'İstanbul Topkapı Üniversitesi', city: 'İstanbul', type: 'vakıf', shortName: 'TOPKAPI' },
  { name: 'İzmir Ekonomi Üniversitesi', city: 'İzmir', type: 'vakıf', shortName: 'İEÜ' },
  { name: 'İzmir Tınaztepe Üniversitesi', city: 'İzmir', type: 'vakıf', shortName: 'TINAZTEPE' },
  { name: 'Kadir Has Üniversitesi', city: 'İstanbul', type: 'vakıf', shortName: 'KHÜ' },
  { name: 'Koç Üniversitesi', city: 'İstanbul', type: 'vakıf', shortName: 'KU' },
  { name: 'Lokman Hekim Üniversitesi', city: 'Ankara', type: 'vakıf', shortName: 'LHÜ' },
  { name: 'Maltepe Üniversitesi', city: 'İstanbul', type: 'vakıf', shortName: 'MALTEPE' },
  { name: 'MEF Üniversitesi', city: 'İstanbul', type: 'vakıf', shortName: 'MEF' },
  { name: 'Ostim Teknik Üniversitesi', city: 'Ankara', type: 'vakıf', shortName: 'OTÜ' },
  { name: 'Özyeğin Üniversitesi', city: 'İstanbul', type: 'vakıf', shortName: 'ÖZÜ' },
  { name: 'Piri Reis Üniversitesi', city: 'İstanbul', type: 'vakıf', shortName: 'PRÜ' },
  { name: 'Sabancı Üniversitesi', city: 'İstanbul', type: 'vakıf', shortName: 'SÜ' },
  { name: 'Sanko Üniversitesi', city: 'Gaziantep', type: 'vakıf', shortName: 'SANKO' },
  { name: 'TOBB Ekonomi ve Teknoloji Üniversitesi', city: 'Ankara', type: 'vakıf', shortName: 'ETÜ' },
  { name: 'TED Üniversitesi', city: 'Ankara', type: 'vakıf', shortName: 'TEDÜ' },
  { name: 'Toros Üniversitesi', city: 'Mersin', type: 'vakıf', shortName: 'TOROS' },
  { name: 'Türk Hava Kurumu Üniversitesi', city: 'Ankara', type: 'vakıf', shortName: 'THK' },
  { name: 'Üsküdar Üniversitesi', city: 'İstanbul', type: 'vakıf', shortName: 'ÜSKÜDAR' },
  { name: 'Yeditepe Üniversitesi', city: 'İstanbul', type: 'vakıf', shortName: 'YEDİTEPE' },
  { name: 'Yeni Yüzyıl Üniversitesi', city: 'İstanbul', type: 'vakıf', shortName: 'YYÜ' },
  { name: 'Ankara Bilim Üniversitesi', city: 'Ankara', type: 'vakıf', shortName: 'ABÜ' },
  { name: 'Birlik Üniversitesi', city: 'Ankara', type: 'vakıf', shortName: 'BİRLİK' },
  { name: 'Ufuk Üniversitesi', city: 'Ankara', type: 'vakıf', shortName: 'UFUK' },
  { name: 'Yaşar Üniversitesi', city: 'İzmir', type: 'vakıf', shortName: 'YAŞAR' },
  { name: 'Alanya Hamdullah Emin Paşa Üniversitesi', city: 'Antalya', type: 'vakıf', shortName: 'AHEP' },
  { name: 'Alanya Alaaddin Keykubat Üniversitesi', city: 'Antalya', type: 'devlet', shortName: 'ALKÜ' },
  { name: 'Antalya Bilim Üniversitesi', city: 'Antalya', type: 'vakıf', shortName: 'ABÜ' },
  { name: 'Avrasya Üniversitesi', city: 'Trabzon', type: 'vakıf', shortName: 'AVRASYA' },
  { name: 'Beykoz Üniversitesi', city: 'İstanbul', type: 'vakıf', shortName: 'BEYKOZ' },
  { name: 'Bursa Özgür Üniversitesi', city: 'Bursa', type: 'vakıf', shortName: 'BOZÜ' },
  { name: 'Çukurova Üniversitesi', city: 'Adana', type: 'devlet', shortName: 'ÇÜ' },
  { name: 'Gazi Üniversitesi (Sağlık)', city: 'Ankara', type: 'devlet', shortName: 'GÜ' },
  { name: 'Gaziosmanpaşa Üniversitesi', city: 'Tokat', type: 'devlet', shortName: 'GOP' },
  { name: 'İstanbul Atlas Üniversitesi', city: 'İstanbul', type: 'vakıf', shortName: 'ATLAS' },
];

async function main() {
  await ds.initialize();
  console.log('Bağlantı kuruldu. Üniversiteler ekleniyor...');

  const table = 'belek_graduate_admission.universities';

  // Varsa atla
  const existing = await ds.query(`SELECT name FROM ${table}`);
  const existingNames = new Set(existing.map((r: any) => r.name));

  let inserted = 0;
  for (const u of UNIVERSITIES) {
    if (existingNames.has(u.name)) continue;
    await ds.query(
      `INSERT INTO ${table} (name, city, type, short_name) VALUES ($1, $2, $3, $4)`,
      [u.name, u.city, u.type, u.shortName ?? null],
    );
    inserted++;
  }

  console.log(`✅ ${inserted} üniversite eklendi. (${existingNames.size} zaten mevcut)`);
  await ds.destroy();
}

main().catch((e) => { console.error(e); process.exit(1); });
